Layout/SpaceInsideBlockBraces:
  EnforcedStyle: space

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Lint/SuppressedException:
  Enabled: false

Style/SymbolProc:
  Enabled: false
